version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-evo
    restart: unless-stopped
    environment:
      POSTGRES_USER: evo
      POSTGRES_PASSWORD: Salesforce1
      POSTGRES_DB: evogames
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
